# Generated by Django 5.1.6 on 2025-08-20 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekOffPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Week Off', max_length=255)),
                ('week_off_type', models.CharField(default='Default', help_text='e.g. Fixed, Rotational, Alternate', max_length=100)),
                ('week_days', models.JSONField(default=['Sunday'], help_text='List of weekdays off')),
                ('week_off_cycle', models.JSONField(default=[1, 2, 3, 4, 5])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_week_off', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_week_off', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
