# Generated by Django 5.1.6 on 2025-06-14 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceWeekOff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekoffpolicy',
            name='week_off_days',
        ),
        migrations.AddField(
            model_name='weekoffpolicy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weekoffpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weekoffpolicy',
            name='week_days',
            field=models.JSONField(default=list, help_text='List of weekdays off'),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_week_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_week_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='week_off_cycle',
            field=models.JSONField(default=[1, 2, 3, 4, 5]),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='week_off_type',
            field=models.CharField(help_text='e.g. Fixed, Rotational, Alternate', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserCustomWeekOff',
        ),
    ]
