# Generated by Django 5.1.6 on 2025-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceWeekOff', '0002_remove_weekoffpolicy_week_off_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='name',
            field=models.CharField(default='Default Week Off', max_length=255),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='week_days',
            field=models.JSONField(default=['Sunday'], help_text='List of weekdays off'),
        ),
        migrations.AlterField(
            model_name='weekoffpolicy',
            name='week_off_type',
            field=models.CharField(default='Default', help_text='e.g. Fixed, Rotational, Alternate', max_length=100),
        ),
    ]
