# Generated by Django 5.1.6 on 2025-06-14 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('system_owner', 'System Owner'), ('organization', 'Organization'), ('admin', 'Admin'), ('user', 'User')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('profile_photo_url', models.CharField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('allow_geo_fencing', models.BooleanField(default=False)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('week_off_policy_ids', models.JSONField(blank=True, null=True)),
                ('shift_ids', models.JSONField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('custom_employee_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('referral_contact_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_no', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('pf_number', models.CharField(blank=True, max_length=30)),
                ('esic_number', models.CharField(blank=True, max_length=30)),
                ('bank_address', models.TextField(blank=True)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='under_admin_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='under_organization_profile_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='own_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemOwnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'system_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='own_system_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_logo', models.CharField(blank=True, max_length=500)),
                ('face_recognition_enabled', models.BooleanField(default=False)),
                ('auto_checkout_enabled', models.BooleanField(default=False)),
                ('auto_checkout_time', models.TimeField(blank=True, null=True)),
                ('auto_shiftwise_checkout_enabled', models.BooleanField(default=False)),
                ('auto_shiftwise_checkout_time', models.TimeField(blank=True, null=True)),
                ('late_punch_enabled', models.BooleanField(default=False)),
                ('late_punch_grace_minutes', models.IntegerField(blank=True, null=True)),
                ('early_exit_enabled', models.BooleanField(default=False)),
                ('early_exit_grace_minutes', models.IntegerField(blank=True, null=True)),
                ('auto_shift_assignment_enabled', models.BooleanField(default=False)),
                ('compensatory_off_enabled', models.BooleanField(default=False)),
                ('custom_week_off_enabled', models.BooleanField(default=False)),
                ('location_tracking_enabled', models.BooleanField(default=False)),
                ('manual_attendance_enabled', models.BooleanField(default=False)),
                ('expense_module_enabled', models.BooleanField(default=False)),
                ('chat_module_enabled', models.BooleanField(default=False)),
                ('group_location_tracking_enabled', models.BooleanField(default=False)),
                ('meeting_module_enabled', models.BooleanField(default=False)),
                ('business_intelligence_reports_enabled', models.BooleanField(default=False)),
                ('payroll_module_enabled', models.BooleanField(default=False)),
                ('location_marking_enabled', models.BooleanField(default=False)),
                ('sandwich_leave_enabled', models.BooleanField(default=False)),
                ('leave_carry_forward_enabled', models.BooleanField(default=False)),
                ('min_hours_for_half_day', models.IntegerField(blank=True, null=True)),
                ('multiple_shift_enabled', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=False)),
                ('ip_restriction_enabled', models.BooleanField(default=False)),
                ('allowed_ip_ranges', models.TextField(blank=True, null=True)),
                ('geofencing_enabled', models.BooleanField(default=False)),
                ('geofence_radius_in_meters', models.IntegerField(blank=True, null=True)),
                ('device_binding_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='own_organization_profile_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_owner', models.ForeignKey(limit_choices_to={'role': 'system_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='under_syster_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='own_organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='under_organization_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='own_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
