# Generated by Django 4.0.8 on 2025-01-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='systemowner',
            old_name='uid',
            new_name='id',
        ),
    ]
