# Generated by Django 5.1.6 on 2025-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0001_initial'),
        ('ServiceShift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_shifts',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='ServiceShift.serviceshift'),
        ),
    ]
