# Generated by Django 5.1.6 on 2025-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0001_initial'),
        ('ServiceShift', '0006_alter_serviceshift_end_time_and_more'),
        ('ServiceWeekOff', '0003_alter_weekoffpolicy_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shift_ids',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='week_off_policy_ids',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift_ids',
            field=models.ManyToManyField(blank=True, related_name='users_shifts', to='ServiceShift.serviceshift'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='week_off_policy_ids',
            field=models.ManyToManyField(blank=True, related_name='users_week_off', to='ServiceWeekOff.weekoffpolicy'),
        ),
    ]
