# Generated by Django 5.1.6 on 2025-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0002_remove_userprofile_shift_ids_and_more'),
        ('LocationControl', '0002_alter_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='shift_ids',
            new_name='shifts',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='week_off_policy_ids',
            new_name='week_offs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users_week_off', to='LocationControl.location'),
        ),
    ]
