# Generated by Django 5.1.6 on 2025-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0003_rename_shift_ids_userprofile_shifts_and_more'),
        ('LocationControl', '0002_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users_location', to='LocationControl.location'),
        ),
    ]
