# Generated by Django 5.1.6 on 2025-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0004_alter_userprofile_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_employee_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
