from django.db import models
from AuthN.models import *
# Create your models here.
class VisitAssignment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    admin = models.ForeignKey(BaseUserModel, on_delete=models.CASCADE)
    organization = models.ForeignKey(BaseUserModel, on_delete=models.CASCADE)
    assigned_user = models.ForeignKey(BaseUserModel, on_delete=models.CASCADE)
    visitor_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    visitor_email = models.EmailField()
    visitor_mobile = models.CharField(max_length=15)
    meeting_date = models.DateField()
    meeting_time = models.TimeField()
    job_title = models.CharField(max_length=255)
    address = models.TextField()
    district = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    segment = models.CharField(max_length=100)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.CharField(max_length=100)
    review = models.CharField(max_length=255)
    comment = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    attachments = models.JSONField()
    start_latitude = models.DecimalField(max_digits=9, decimal_ssplaces=6)
    start_longitude = models.DecimalField(max_digits=9, decimal_places=6)
    end_latitude = models.DecimalField(max_digits=9, decimal_places=6)
    end_longitude = models.DecimalField(max_digits=9, decimal_places=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
