# Generated by Django 5.1.6 on 2025-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskControl', '0002_tasktype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(blank=True, default='Service Task', max_length=255, null=True),
        ),
    ]
