# Generated by Django 5.1.6 on 2025-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
