# Generated by Django 5.1.6 on 2025-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
