# Generated by Django 5.1.6 on 2025-06-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holiday', '0002_holiday_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_holiday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_holiday', to=settings.AUTH_USER_MODEL),
        ),
    ]
