# Generated by Django 5.1.6 on 2025-06-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthN', '0005_alter_userprofile_custom_employee_id'),
        ('UserActivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to='AuthN.adminprofile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, to='AuthN.organizationprofile'),
        ),
    ]
