# Generated by Django 5.1.6 on 2025-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0002_alter_expensecategory_admin_alter_expensecategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(default='Service Expense', max_length=255),
        ),
    ]
