# Generated by Django 5.1.6 on 2025-06-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0003_alter_expensecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.CharField(default='Default Service Expense', max_length=255),
        ),
    ]
