# Generated by Django 5.1.6 on 2025-06-09 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_name', models.CharField(max_length=100)),
                ('is_inactive', models.BooleanField(default=False)),
                ('shift_duration', models.DurationField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_shifts', to='AuthN.adminprofile')),
            ],
        ),
    ]
