# Generated by Django 5.1.6 on 2025-06-14 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthN', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration_minutes', models.IntegerField()),
                ('is_night_shift', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.adminprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.organizationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('assignment_type', models.CharField(default='Auto', max_length=50)),
                ('assigned_by', models.UUIDField(blank=True, null=True)),
                ('assignment_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.adminprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.organizationprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceShift.serviceshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
