# Generated by Django 5.2.8 on 2025-11-29 14:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(blank=True, default='Default Shift', max_length=255, null=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(9, 0))),
                ('break_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_night_shift', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_shift', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_shift', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
