# Generated by Django 5.1.6 on 2025-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceShift', '0002_alter_serviceshift_admin_alter_serviceshift_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshift',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='break_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='is_night_shift',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='shift_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
