# Generated by Django 5.1.6 on 2025-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceShift', '0003_serviceshift_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
