# Generated by Django 5.1.6 on 2025-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceShift', '0004_serviceshift_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshift',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='shift_name',
            field=models.CharField(blank=True, default='Default Shift', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
