# Generated by Django 5.1.6 on 2025-06-14 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceShift', '0005_alter_serviceshift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshift',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='serviceshift',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
