# Generated by Django 5.1.6 on 2025-06-17 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveControl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('admin', 'code', 'is_active')},
        ),
    ]
