# Generated by Django 5.1.6 on 2025-06-17 00:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveControl', '0002_alter_leavetype_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together={('user', 'leave_type', 'year', 'is_active')},
        ),
    ]
