# Generated by Django 5.1.6 on 2025-06-16 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceShift', '0007_alter_serviceshift_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_working_minutes', models.IntegerField(blank=True, null=True)),
                ('break_duration_minutes', models.IntegerField(default=0)),
                ('attendance_status', models.CharField(max_length=50)),
                ('check_in_location', models.TextField(blank=True, null=True)),
                ('check_out_location', models.TextField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('marked_by', models.CharField(max_length=100)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_attendnace', to=settings.AUTH_USER_MODEL)),
                ('assign_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_attendance', to='ServiceShift.serviceshift')),
                ('organization', models.ForeignKey(limit_choices_to={'role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_attendnace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
