# Generated by Django 5.1.6 on 2025-06-14 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_working_hours', models.DurationField(blank=True, null=True)),
                ('break_duration_minutes', models.IntegerField(default=0)),
                ('attendance_status', models.CharField(max_length=50)),
                ('check_in_location', models.TextField(blank=True, null=True)),
                ('check_out_location', models.TextField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('marked_by', models.CharField(max_length=100)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.adminprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.organizationprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthN.userprofile')),
            ],
        ),
    ]
