# Generated by Django 5.1.6 on 2025-06-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_exit_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
