"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%*_y9f1acqxiy(gxfgk2*a##=^0a9tm^g=*)ex#v+n=m#&_&_6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = ['http://localhost:3000']
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',  # Example of a third-party app
    'rest_framework_simplejwt',
    'corsheaders',
    # "rest_framework.authtoken",
]

LOCAL_APPS = [
    'AuthN',        
    'WorkforceProfile',
    'Holiday', 
    'ServiceShift',
    'ServiceWeekOff',
    'WorkLog',
    'Expenditure',
    'UserActivity',
    'ReportLog',
    'PayrollSystem',
    'TaskControl',
    'LocationControl',
    'LeaveControl',
    'VisitControl',
    'AssetManagement',
    'NotesManagement',
    'BroadcastManagement',
    'NotificationControl',
    'HelpdeskManagement',
    'PerformanceManagement',
    'OnboardingManagement',
    'HRAnalytics',
    'OrganizationManagement',
    ]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
CORS_ALLOW_ALL_ORIGINS = True  # OR use CORS_ALLOWED_ORIGINS = ['http://localhost:3000']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

USER_ID_FIELD = 'uid'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "AuthN.BaseUserModel"


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=3000000),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = False  # Use timezone-aware datetime
TIME_ZONE = 'Asia/Kolkata'  # Set your timezone to Indian Standard Time


import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis as message broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Redis as result backend
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False

# Celery Beat Schedule (Periodic Tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Auto-checkout tasks - Run every 5 minutes
    'general-auto-checkout-every-5-minutes': {
        'task': 'general_auto_checkout_task',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    'shiftwise-auto-checkout-every-5-minutes': {
        'task': 'shiftwise_auto_checkout_task',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    
    # Notification tasks - Run every minute
    'send-scheduled-notifications-every-minute': {
        'task': 'send_scheduled_notifications_task',
        'schedule': crontab(minute='*'),  # Every minute
    },
    'send-broadcast-notifications-every-minute': {
        'task': 'send_broadcast_notifications_task',
        'schedule': crontab(minute='*'),  # Every minute
    },
    
    # Monthly tasks - Run on 1st of every month at 2 AM
    'process-monthly-payroll': {
        'task': 'process_monthly_payroll_task',
        'schedule': crontab(hour=2, minute=0, day_of_month=1),  # 1st of every month at 2 AM
    },
    'process-leave-accrual-monthly': {
        'task': 'process_leave_accrual_task',
        'schedule': crontab(hour=3, minute=0, day_of_month=1),  # 1st of every month at 3 AM
    },
    'update-asset-depreciation-monthly': {
        'task': 'update_asset_depreciation_task',
        'schedule': crontab(hour=4, minute=0, day_of_month=1),  # 1st of every month at 4 AM
    },
    
    # Weekly tasks - Run every Monday at 9 AM
    'process-expense-reimbursements-weekly': {
        'task': 'process_expense_reimbursements_task',
        'schedule': crontab(hour=9, minute=0, day_of_week=1),  # Every Monday at 9 AM
    },
    
    # Daily tasks - Run at midnight
    'attendance-auto-close-daily': {
        'task': 'attendance_auto_close_task',
        'schedule': crontab(hour=0, minute=0),  # Every day at midnight
    },
    'late-early-detection-daily': {
        'task': 'late_early_detection_task',
        'schedule': crontab(hour=1, minute=0),  # Every day at 1 AM
    },
    'birthday-anniversary-alerts-daily': {
        'task': 'birthday_anniversary_alerts_task',
        'schedule': crontab(hour=8, minute=0),  # Every day at 8 AM
    },
    'data-backup-daily': {
        'task': 'data_backup_task',
        'schedule': crontab(hour=2, minute=0),  # Every day at 2 AM
    },
    
    # Monthly tasks - Additional
    'leave-carry-forward-yearly': {
        'task': 'leave_carry_forward_task',
        'schedule': crontab(hour=5, minute=0, day_of_month=1),  # 1st of every month at 5 AM
    },
    
    # Organization tasks - Run daily
    'check-organization-expiry-daily': {
        'task': 'check_organization_expiry_task',
        'schedule': crontab(hour=6, minute=0),  # Every day at 6 AM
    },
    'send-renewal-reminders-daily': {
        'task': 'send_renewal_reminders_task',
        'schedule': crontab(hour=9, minute=0),  # Every day at 9 AM
    },
    
    # Security tasks - Run daily
    'token-cleanup-daily': {
        'task': 'token_cleanup_task',
        'schedule': crontab(hour=3, minute=0),  # Every day at 3 AM
    },
    'suspicious-login-detection-hourly': {
        'task': 'suspicious_login_detection_task',
        'schedule': crontab(minute=0),  # Every hour
    },
}

